### ISSUE TITLE
Commandeer 0.3.5 not detecting Docker on macOS Catalina 10.15.1

### ISSUE THREAD

**Issue by matthewalr** [commandeer/open#27]
Setup a new MacBook Pro running 10.15.1. Downloaded Docker Desktop, ran a few test containers. Installed Commandeer 0.3.5. Commandeer can't detect Docker to setup LocalStack. 

<img width="1165" alt="Screen Shot 2019-12-04 at 12 11 40 AM" src="https://user-images.githubusercontent.com/4644552/70124969-bc313380-162a-11ea-8add-ce161c6f9fed.png">

**Comment by rv-amadden** [comment]
Same thing on Mojave 10.14.6.

**Comment by fsproru** [comment]
@matthewalr @rv-amadden would you mind sending the output of `whcih docker` ?

**Comment by rv-amadden** [comment]
```console
amadden:~$ which docker
/usr/local/bin/docker
```

**Comment by fsproru** [comment]
Thanks @rv-amadden, @matthewalr we'll use `docker--version` in the next version, this way we can also display which version is installed on the UI.

Still weird that the which command doesn't produce the desired result. That being said, running `docker --version` is a better solution anyway since it doesn't involve calling a different command, i.e. `which`.

**Comment by bwship** [comment]
Going to close this, as the change will be coming out in our next release.
