### ISSUE TITLE
Localstack doesn't find homebrew docker installation

### ISSUE THREAD

**Issue by marc-guenther** [commandeer/open#55]
The Localstack Install complains:
```
Docker : /bin/sh: docker: command not found
check Python : Python 2.7.10
close Pip : /bin/sh: pip: command not found
close LocalStack CLI : /bin/sh: localstack: command not found
```

Of these, only the last one is correct, the other two are in `/usr/local/bin` (installed through Homebrew)

I cannot find any option to set the PATH from inside Commandeer.

**Comment by john20xdoe** [comment]
Any workaround for this?
Tried to create a symlink in /bin for /usr/local/bin/docker 
    $ ln -s /usr/local/bin/docker docker 
but "Operation not permitted". 
This is on MacOS Catalina, if that helps.

**Comment by fsproru** [comment]
Hey guys, thanks for reporting it. These statuses can be a little misleading at the moment as we work through it.

The only thing you need to run LocalStack is Docker. Since we talk to Docker socket directly. As long as you have Docker running on your local machine and the Docker status is green on the top right in Commandeer, you should be able to use LocalStack using Commandeer.

Let me know if you run into any issues.

**Comment by john20xdoe** [comment]
@fsproru THanks for the info. Docker is green and Localstack is able to start up its individual AWS services (manual one-by-one click on Start buttons or Start All). 
I guess we don't need to use Localstack Install for now while issues are being resolved.

**Comment by fsproru** [comment]
Thanks @john20xdoe, we’ll also update the LocalStack status and Serverless status to use Docker status since that’s the only thing we need to run them.
