### ISSUE TITLE
support aws cli config files and profiles

### ISSUE THREAD

**Issue by ebarault** [commandeer/open#58]
Hi,
Could Commandeer make use of AWS cli config files and profiles?
~/.aws/credentials
~/.aws/config

It's usually the best practice for any soft leveraging aws sdks as any aws devs would use those already.

Furthermore the use of profiles is critical when using a unique AWS account (with credentials) to access ressources in different AWS accounts through IAM roles.

**Comment by fsproru** [comment]
Thanks @ebarault, it’s a great feature to add to Commandeer, added it to the backlog 👍

**Comment by bwship** [comment]
@ebarault - yes this is in the pipeline.  I am still trying to figure out how we are going to do SSO and short-loived keys in the system.  Are you saying that you crednetials file auto updates with new refreshed keys when you are assuming a role.  Because some ways I have been thinking about it is that you connect to an account in Commandeer, and would press a button to get new keys, and it would popup the sso amazon webpage, and you login, and get those short-lived keys.  But, I'd love to hear your thoughts expanded upon.

**Comment by ebarault** [comment]
@bwship could you precise what you mean by SSO? do you mean AWS SSO (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html) ?

If yes, that's a more advanced feature, and i'd suggest moving on gradually with this by first integrating aws cli config files support, since as you can see in the link i shared, the sso config for the cli and sdks should end-up in those config files too.

I have never used it in the context of a sdk though, so i could not describe the exact workflow: does the sdk returns the sso url ?  or does it attempt to open a web browser directly ? This has to be tested.

But first, i think basic aws credentials config files and profiles support would unlock many benefits.

Plus, it's a pretty worrying to have to paste our aws credentials in Commandeer's gui next to a window stating "upload" which could make oneself think the credentials are being uploaded to some 3rd party website. The usual workflow is for devs on their laptops is: once you have configured your aws cli, any sdk makes use of it and don't ask for your credentials.

**Comment by jewelsjacobs** [comment]
Unfortunately not being able to use ~/.aws/credentials, ~/.aws/config is a show stopper for me 😞

**Comment by bwship** [comment]
@ebarault - great point about the Upload.  It is not uploading it, it is simply storing it in the Commandeer data folder on your computer.  We will change the wording there so that this is not confusing.  We are going to do an integration with the credentials and config file.  This is a great point, and I think an easy win to pull off.

**Comment by bwship** [comment]
@jewelsjacobs -Yea, for now you could simply copy and paste the credentials from the credentials file into Commandeer.  These creds never hit our servers.  They are only used to connect to your AWS instance via the SDK under the hood of the app.  That said, we are going to prioritize pulling in these creds from the ~/.aws files to make it a little more seamless for the users.  Thank you for the input on it!

**Comment by bwship** [comment]
@jewelsjacobs - Also, as per your comment about the role based.  Does taht mean your .aws/credentials file updates with new rotating keys often for the same account?

**Comment by bwship** [comment]
@ebarault and @jewelsjacobs - Below is a screenshot of what I am working on in terms of allowing you to either enter keys manually, uploading a credentials.csv file, or selecting from a profile in your .aws/credentials file.  Let me know what you think if you get a chance.  

<img width="683" alt="add-account2" src="https://user-images.githubusercontent.com/1326114/116955645-1fc8f180-ac61-11eb-82a7-f21a6dee56df.png">

**Comment by bwship** [comment]
@ebarault and @jewelsjacobs - Great news!  We are rolling this feature out tomorrow in version 1.9.1.  You can read all about it on our release page.   https://docs.getcommandeer.com/releases/latest/version-1.9.1-may-11-2021/ - Going to close out this issue.  Let me know how it works for you.
