### ISSUE TITLE
Empty files

### ISSUE THREAD

**Issue by olafura** [commandeer/open#6]
Are a lot of the files supposed to be empty?

https://github.com/commandeer/open/blob/development/templates/commandeer/cli/serviceCodeGenerator.ts
https://github.com/commandeer/open/blob/development/templates/commandeer/tank-service/main.ts
https://github.com/commandeer/open/blob/development/templates/commandeer/tank-service/package.json

etc...

**Comment by fsproru** [comment]
Hi @olafura, once the package is submitted, we'll take it further by integrating it into Commandeer. That's where we'll fill out the blanks.

* I would keep `serviceCodeGenerator.ts` empty for now.
* You can add any of your setup code to `main.ts` if you have any, not all services have some extra setup code since the setup is driven from the UI.
* `package.json` will need to filled out with any dependencies you use. I would put them in the `devDependencies` section of package.json while you're developing.

Let us know if you have any further questions. We're looking forward to seeing what you can do with Commandeer.

**Comment by fsproru** [comment]
Closing it, @olafura let us know if you have any questions.

**Comment by bwship** [comment]
@olafura - you can now run yarn serve form the tank-service folder to get this running.  You can check out the pr here.  Let us know if you have any issues.  Tank battles coming soon! https://github.com/commandeer/open/pull/10
