### ISSUE TITLE
Javascript error on startup

### ISSUE THREAD

**Issue by ssanri** [commandeer/open#85]
@fsproru Was there a major change on background events? I keep getting this error this morning when I try to start the app 
![image](https://user-images.githubusercontent.com/53793378/100632071-62754f00-32fa-11eb-8781-ad25140d05e6.png)

**Comment by fsproru** [comment]
Thanks @ssanri, @bwship could you take a look on Windows?

**Comment by fsproru** [comment]
Hi @ssanri, we tried to reproduce the issue and the app stands up and works normally on Windows. Would you mind trying some of the following:
* Reinstall the newest version of the app from the [Download Page](https://getcommandeer.com/download)
* If the app stands up for some time, then going into your account and clearing the cache like on this screenshot
<img width="1091" alt="Screen Shot 2020-11-30 at 11 29 01 AM" src="https://user-images.githubusercontent.com/1017606/100655327-f990d580-32ff-11eb-93f2-4638ea2c4335.png">

* If the app doesn't stand up, then opening your data folder and deleting the cache folders manually, then starting the app again like in this screenshot.
<img width="1804" alt="d" src="https://user-images.githubusercontent.com/1017606/100655357-031a3d80-3300-11eb-832a-23549f10f8d6.png">
* Also if there is something specific you do in the app prior to the crash, please let us know.

**Comment by fsproru** [comment]
@ssanri, we reproduced it and working on the fix. In the meantime, there is a workaround.

What's happening is that after the upgrade to 1.5.0, you most likely started the app, did some work, and then closed it. In 1.5.0 we started to put some of the work on the background. When the window is closed it leaves the background process on and it prevents launching a new window when you start it again (since we only allow a single instance of the app open at the time). Should be a straightforward fix to close the background process too when the app quits.

In the meantime, you can open task manager, end the leftover Commandeer processes, and start Commandeer again.

<img width="666" alt="Screen Shot 2020-11-30 at 12 23 47 PM" src="https://user-images.githubusercontent.com/1017606/100661131-d8cc7e00-3307-11eb-8660-1590350f4935.png">

**Comment by ssanri** [comment]
@fsproru Thank you Alex. After I posted the issue I noticed 3 instances running in TaskManager. I ended those and started Commandeer it worked as expected.

**Comment by fsproru** [comment]
@ssanri, thank you, we have a fix for it, working on the 1.5.1 release now to get it out. In the meantime, you can just close the lingering processes when you restart as a workaround.

**Comment by fsproru** [comment]
@ssanri 1.5.1 is released with the fix for duplicate processes.
